### ISSUE TITLE
Compiling custom vertex and fragment shader

### ISSUE THREAD

**Issue by rimitalahiri** [peepo/openGL-RPi-tutorial#7]
I have written a custom fragment shader and vertex shader as following certain examples....

Vertex Shader:
```
attribute vec4 position;
attribute vec4 inputTextureCoordinate;

varying vec2 textureCoordinate;

void main()
{
    gl_Position = position;
    textureCoordinate = inputTextureCoordinate.xy;
}
```
Fragment Shader:
```
varying highp vec2 textureCoordinate;

uniform sampler2D inputImageTexture;

void main()
{
    gl_FragColor = texture2D(inputImageTexture, textureCoordinate);
}
```

Now I am unable to write the supporting  C program as done in each of the tutorials that will integrate these vertex and fragment shaders. Please help.

Thank you.

**Comment by peepo** [comment]
off topic
