### ISSUE TITLE
Got error "* failed to add service - already in use?"

### ISSUE THREAD

**Issue by nvti** [peepo/openGL-RPi-tutorial#8]
I got error "* failed to add service - already in use?" when try to run `tutorial01_first_screen`
I set `gpu_mem` to 256MB on raspberry pi3+
Can you help me to run it?

**Comment by peepo** [comment]
did you read the related readme:

use dispmanx to start screen

**Comment by nvti** [comment]
But how to use dispmanx? Sorry because I am newbie. Can you guide?

**Comment by peepo** [comment]
Google is your friend, try:

https://github.com/raspberrypi/firmware/tree/master/opt/vc/src/hello_pi/hello_dispmanx
